### ISSUE TITLE
AI chat window 'Ask AI' and Project Settings screens are missing

### ISSUE THREAD

**Issue by datacrud8** [fiston-user/contract-analysis-yt#1]
Hi,
Thank you for sharing the wonderful project.
I tried to run this project locally, it's running but few features are missing like AI chat "Ask AI' and the Project Settings , Global Settings are missing. Also stripe membership activated but still not showing, checked the repo code , class files are missing in repo.
Can you please share the particular files or repo access for client & server.
Planning to evaluate this app with full features with our documents, it would help to bring a few more features. 

Thank you.

**Comment by fiston-user** [comment]
Hello sorry for late reply yeah ofc, lets talk on my dc i will be happy to provide u the rest: https://discord.com/invite/cMNSUQvYRt
