### ISSUE TITLE
AI section not working 

### ISSUE THREAD

**Issue by prince07** [fiston-user/contract-analysis-yt#2]
{"error":"Failed to detect contract type"}

Request URL:
http://localhost:8080/contracts/detect-type
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
[::1]:8080
Referrer Policy:
strict-origin-when-cross-origin
access-control-allow-credentials:
true
access-control-allow-origin:
http://localhost:3003
connection:
keep-alive
content-length:
42
content-security-policy:
default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
content-type:
application/json; charset=utf-8
cross-origin-opener-policy:
same-origin
cross-origin-resource-policy:
same-origin
date:
Sun, 20 Oct 2024 09:40:16 GMT
etag:
W/"2a-XF+hW11LwHDUPPb07tahbLHgRMQ"
keep-alive:
timeout=5
origin-agent-cluster:
?1
referrer-policy:
no-referrer
strict-transport-security:
max-age=31536000; includeSubDomains
vary:
Origin
x-content-type-options:
nosniff
x-dns-prefetch-control:
off
x-download-options:
noopen
x-frame-options:
SAMEORIGIN
x-permitted-cross-domain-policies:
none
x-xss-protection:
0
accept:
application/json, text/plain, */*
accept-encoding:
gzip, deflate, br, zstd
accept-language:
en-US,en;q=0.9
connection:
keep-alive
content-length:
49856
content-type:
multipart/form-data; boundary=----WebKitFormBoundarytVwLtlQKp8psqbyQ
cookie:
__stripe_mid=28621ecd-59ae-4fd6-b0e0-9b1cc0fa9bacbe4662; connect.sid=s%3A1JFOkMw6fADvNE2Qe-YjJGEBJC-8jvRE.Lcb1KHjAbsLkEgPTXLm%2BbvwAGaAmMd9BS66vcLVxFPs
host:
localhost:8080
origin:
http://localhost:3003
referer:
http://localhost:3003/
sec-ch-ua:
"Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
sec-ch-ua-mobile:
?0
sec-ch-ua-platform:
"macOS"
sec-fetch-dest:
empty
sec-fetch-mode:
cors
sec-fetch-site:
same-site
user-agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36

**Comment by fiston-user** [comment]
message me on discord, cause without seeing the actually log error in ur backend server cant know whats the issue is other than the 500 which shows its server errorr:  https://discord.com/invite/cMNSUQvYRt
